# Generated by Django 2.2.5 on 2019-10-27 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20191027_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='last_action',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
