# Generated by Django 2.2.5 on 2019-11-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20191027_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='last_action',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
