# Generated by Django 2.2.5 on 2019-11-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20191109_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='last_action',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
