# Generated by Django 2.2.5 on 2019-11-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20191109_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='last_action',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
